#! /usr/bin/env php
<?php

require 'vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

// var_dump(getenv('DB_HOST'));

$app = new Symfony\Component\Console\Application("ANDS Log Utilities", "0.1");
$app->add(new MinhD\ANDSLogUtil\ProcessCommand);
$app->run();